apiVersion: v1 
kind: Pod 
metadata: 
  name: centos-pod 
spec:
  containers:
  - name: centos-container  
    image: centos:7  
    env:
    - name: URL
      value: www.devops.com 
    - name: DOMAIN
      value: roboshop.internal