apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-pod 
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"