# Creates a deployment set 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80 
--- 

apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
spec:
  # type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80              # Port number of the service that it has to listen on 
      targetPort: 80        # Port number of the container that it has to forward to
